method: random                                              # grid, random, bayes
metric:
  name: best_val_loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.0001, 0.00005, 0.00001]

  # batch_size:
    # values: [16, 32, 64]

  dropout_prob:
    min: 0.1
    max: 0.5

  N_embed:
    values: [128, 256, 512]

  num_attention_heads:
    values: [8, 16, 32]

  num_encoder_layers:
    values: [4, 6, 8]

  # weight_decay:
    # values: [0.0, 0.01, 0.001]

  # lr_decay_step:
    # values: [5, 10]
    # values: [5, 10, 20]

  # lr_decay_gamma:
    # min: 0.1
    # max: 0.5
